package scrap

var EduLibMap = map[string]LibInfo{
	"서울특별시교육청강남도서관": {
		libName:  "서울특별시교육청강남도서관",
		libCode:  "111003",
		homepage: "https://gnlib.sen.go.kr/gnlib",
		pageName: "gnlib",
	},
	"서울특별시교육청강동도서관": {
		libName:  "서울특별시교육청강동도서관",
		libCode:  "111004",
		homepage: "https://gdlib.sen.go.kr/gdlib",
		pageName: "gdlib",
	},
	"서울특별시교육청강서도서관": {
		libName:  "서울특별시교육청강서도서관",
		libCode:  "111005",
		homepage: "https://gslib.sen.go.kr/gslib",
		pageName: "gslib",
	},
	"서울특별시교육청개포도서관": {
		libName:  "서울특별시교육청개포도서관",
		libCode:  "111006",
		homepage: "https://gplib.sen.go.kr/gplib",
		pageName: "gplib",
	},
	"서울특별시교육청고덕평생학습관": {
		libName:  "서울특별시교육청고덕평생학습관",
		libCode:  "111007",
		homepage: "https://gdllc.sen.go.kr/gdllc",
		pageName: "gdllc",
	},
	"서울특별시교육청고척도서관": {
		libName:  "서울특별시교육청고척도서관",
		libCode:  "111008",
		homepage: "https://gclib.sen.go.kr/gclib",
		pageName: "gclib",
	},
	"서울특별시교육청구로도서관": {
		libName:  "서울특별시교육청구로도서관",
		libCode:  "111009",
		homepage: "https://grlib.sen.go.kr/grlib",
		pageName: "grlib",
	},
	"서울특별시교육청남산도서관": {
		libName:  "서울특별시교육청남산도서관",
		libCode:  "111010",
		homepage: "https://nslib.sen.go.kr/nslib",
		pageName: "nslib",
	},
	"서울특별시교육청노원평생학습관": {
		libName:  "서울특별시교육청노원평생학습관",
		libCode:  "111022",
		homepage: "https://nwllc.sen.go.kr/nwllc",
		pageName: "nwllc",
	},
	"서울특별시교육청도봉도서관": {
		libName:  "서울특별시교육청도봉도서관",
		libCode:  "111011",
		homepage: "https://dblib.sen.go.kr/dblib",
		pageName: "dblib",
	},
	"서울특별시교육청동대문도서관": {
		libName:  "서울특별시교육청동대문도서관",
		libCode:  "111012",
		homepage: "https://ddmlib.sen.go.kr/ddmlib",
		pageName: "ddmlib",
	},
	"서울특별시교육청동작도서관": {
		libName:  "서울특별시교육청동작도서관",
		libCode:  "111013",
		homepage: "https://djlib.sen.go.kr/djlib",
		pageName: "djlib",
	},
	"서울특별시교육청마포평생학습관": {
		libName:  "서울특별시교육청마포평생학습관",
		libCode:  "111014",
		homepage: "https://mpllc.sen.go.kr/mpllc",
		pageName: "mpllc",
	},
	"서울특별시교육청마포평생학습관아현분관": {
		libName:  "서울특별시교육청마포평생학습관아현분관",
		libCode:  "111031",
		homepage: "https://ahyon.sen.go.kr/ahyon",
		pageName: "ahyon",
	},
	"서울특별시교육청서대문도서관": {
		libName:  "서울특별시교육청서대문도서관",
		libCode:  "111016",
		homepage: "https://sdmlib.sen.go.kr/sdmlib",
		pageName: "sdmlib",
	},
	"서울특별시교육청서울시립어린이도서관": {
		libName:  "서울특별시교육청서울시립어린이도서관",
		libCode:  "111017",
		homepage: "https://childlib.sen.go.kr/childlib",
		pageName: "childlib",
	},
	"서울특별시교육청송파도서관": {
		libName:  "서울특별시교육청송파도서관",
		libCode:  "111030",
		homepage: "https://splib.sen.go.kr/splib",
		pageName: "splib",
	},
	"서울특별시교육청양천도서관": {
		libName:  "서울특별시교육청양천도서관",
		libCode:  "111015",
		homepage: "https://yclib.sen.go.kr/yclib",
		pageName: "yclib",
	},
	"서울특별시교육청영등포평생학습관": {
		libName:  "서울특별시교육청영등포평생학습관",
		libCode:  "111018",
		homepage: "https://ydpllc.sen.go.kr/ydpllc",
		pageName: "ydpllc",
	},
	"서울특별시교육청용산도서관": {
		libName:  "서울특별시교육청용산도서관",
		libCode:  "111019",
		homepage: "https://yslib.sen.go.kr/yslib",
		pageName: "yslib",
	},
	"서울특별시교육청정독도서관": {
		libName:  "서울특별시교육청정독도서관",
		libCode:  "111020",
		homepage: "https://jdlib.sen.go.kr/jdlib",
		pageName: "jdlib",
	},
	"서울특별시교육청종로도서관": {
		libName:  "서울특별시교육청종로도서관",
		libCode:  "111021",
		homepage: "https://jnlib.sen.go.kr/jnlib",
		pageName: "jnlib",
	},
}

var LibNameArr = []string{
	"서울특별시교육청강남도서관",
	"서울특별시교육청강동도서관",
	"서울특별시교육청강서도서관",
	"서울특별시교육청개포도서관",
	"서울특별시교육청고덕평생학습관",
	"서울특별시교육청고척도서관",
	"서울특별시교육청구로도서관",
	"서울특별시교육청남산도서관",
	"서울특별시교육청노원평생학습관",
	"서울특별시교육청도봉도서관",
	"서울특별시교육청동대문도서관",
	"서울특별시교육청동작도서관",
	"서울특별시교육청마포평생학습관",
	"서울특별시교육청마포평생학습관아현분관",
	"서울특별시교육청서대문도서관",
	"서울특별시교육청서울시립어린이도서관",
	"서울특별시교육청송파도서관",
	"서울특별시교육청양천도서관",
	"서울특별시교육청영등포평생학습관",
	"서울특별시교육청용산도서관",
	"서울특별시교육청정독도서관",
	"서울특별시교육청종로도서관",
}
